echo instead of error in install_tools

diff --git a/scripts/install_tools b/scripts/install_tools
--- a/scripts/install_tools
+++ b/scripts/install_tools
@@ -50,7 +50,7 @@ lustrec_branch="master"
 zustre_url="https://github.com/coco-team/zustre.git"
 zustre_branch="master"
 kind2_url="https://github.com/kind2-mc/kind2.git"
-kind2_branch="develop"
+kind2_branch="master"
 
 #####################
 # General functions #
@@ -614,29 +614,29 @@ function error_patch() {
 
 function error_configure() {
     if (( verbose == 0 )); then
-        error "Error while configuring $1. see $log_file_orig for more details."
+        echo "Error while configuring $1. see $log_file_orig for more details."
     else
-        error "Error while configuring $1."
+        echo "Error while configuring $1."
     fi
-    exit 9
+    # exit 9
 }
 
 function error_make() {
     if (( verbose == 0 )); then
-        error "Error while building $1. see $log_file_orig for more details."
+        echo "Error while building $1. see $log_file_orig for more details."
     else
-        error "Error while building $1."
+        echo "Error while building $1."
     fi
-    exit 10
+    # exit 10
 }
 
 function error_install() {
     if (( verbose == 0 )); then
-        error "Error while installing $1. see $log_file_orig for more details."
+        echo "Error while installing $1. see $log_file_orig for more details."
     else
-        error "Error while installing $1."
+        echo "Error while installing $1."
     fi
-    exit 11
+    # exit 11
 }
 
 function error_test() {
