disbale Zustre in installation script

diff --git a/scripts/install_tools b/scripts/install_tools
--- a/scripts/install_tools
+++ b/scripts/install_tools
@@ -721,75 +721,75 @@ fi
 # Install zustre #
 ##################
 zustre_failed=0
-if [ $lustrec_failed -eq 1 -o $spacer_failed -eq 1 ]; then
-    error_msg "Skipping Zustre: dependancies Lustrec or spacer installation has failed"
-else
-    if [[ -x "$install_dir/bin/zustre" ]]; then
-        progress "Using already built ${cgreen}zustre"
-    else
-        progress "Installing ${cgreen}zustre${coff}${cbold} from upstream repository"
+# if [ $lustrec_failed -eq 1 -o $spacer_failed -eq 1 ]; then
+#     error_msg "Skipping Zustre: dependancies Lustrec or spacer installation has failed"
+# else
+#     if [[ -x "$install_dir/bin/zustre" ]]; then
+#         progress "Using already built ${cgreen}zustre"
+#     else
+#         progress "Installing ${cgreen}zustre${coff}${cbold} from upstream repository"
 
-        git_clone "$zustre_url" "$zustre_branch" "$build_dir/zustre"
+#         git_clone "$zustre_url" "$zustre_branch" "$build_dir/zustre"
 
-        cd "$build_dir/zustre"
+#         cd "$build_dir/zustre"
 
-        mkdir build
-        cd build
+#         mkdir build
+#         cd build
 
-        progress_run cmake \
-            -DCMAKE_BUILD_TYPE=Release \
-            -DCMAKE_INSTALL_PREFIX="$install_dir" \
-            -DLUSTREC_ROOT="$install_dir" \
-            -DLUSTREC_INCLUDE_DIR="$install_dir/include/lustrec" \
-            -DZ3_ROOT="$install_dir/spacer" \
-            .. || {
-            error_configure zustre;
-            zustre_failed=1;
-        }
-        if (( ! zustre_failed )); then
-            progress_run cmake --build . || {
-                error_make zustre;
-                zustre_failed=1;
-            }
-        fi
-        if (( ! zustre_failed )); then
-            progress_run cmake --build . --target install || {
-                error_install zustre;
-                zustre_failed=1;
-            }
-        fi
-        command_exists zustre || {
-                error_msg "zustre is not properly installed";
-                zustre_failed=1;
-            }
-    fi
+#         progress_run cmake \
+#             -DCMAKE_BUILD_TYPE=Release \
+#             -DCMAKE_INSTALL_PREFIX="$install_dir" \
+#             -DLUSTREC_ROOT="$install_dir" \
+#             -DLUSTREC_INCLUDE_DIR="$install_dir/include/lustrec" \
+#             -DZ3_ROOT="$install_dir/spacer" \
+#             .. || {
+#             error_configure zustre;
+#             zustre_failed=1;
+#         }
+#         if (( ! zustre_failed )); then
+#             progress_run cmake --build . || {
+#                 error_make zustre;
+#                 zustre_failed=1;
+#             }
+#         fi
+#         if (( ! zustre_failed )); then
+#             progress_run cmake --build . --target install || {
+#                 error_install zustre;
+#                 zustre_failed=1;
+#             }
+#         fi
+#         command_exists zustre || {
+#                 error_msg "zustre is not properly installed";
+#                 zustre_failed=1;
+#             }
+#     fi
 
     
-    if (( ! zustre_failed )); then
+#     if (( ! zustre_failed )); then
         
-        success "${cgreen}zustre${coff}${cbold} successfully installed"
-        if (( ! z3_failed )); then
-            # update z3 binary by original z3 and not spacer.
-            cp "$install_dir/z3/bin/z3" "$install_dir/bin/z3"
-        fi
-        if [[ -f "$build_dir/zustre/tests/two_counters.lus" ]]; then
-            progress "Testing zustre on a simple example"
-            zustre_output=$(run_log_debug zustre --xml "$build_dir/zustre/tests/two_counters.lus" 2>&1) || {
-                error_test zustre;
-                zustre_failed=1;
-            }
-            (( verbose >= 1 )) && echo "$zustre_output"
-            if (( ! zustre_failed )); then
-                [[ "$zustre_output" == *"<Answer>SAFE</Answer>"* ]] || {
-                    error_test zustre;
-                    zustre_failed=1;
-                }
-            fi
-        fi
-    else
-        error_msg "Skipping Zustre: zustre installation, failed"
-    fi
-fi
+#         success "${cgreen}zustre${coff}${cbold} successfully installed"
+#         if (( ! z3_failed )); then
+#             # update z3 binary by original z3 and not spacer.
+#             cp "$install_dir/z3/bin/z3" "$install_dir/bin/z3"
+#         fi
+#         if [[ -f "$build_dir/zustre/tests/two_counters.lus" ]]; then
+#             progress "Testing zustre on a simple example"
+#             zustre_output=$(run_log_debug zustre --xml "$build_dir/zustre/tests/two_counters.lus" 2>&1) || {
+#                 error_test zustre;
+#                 zustre_failed=1;
+#             }
+#             (( verbose >= 1 )) && echo "$zustre_output"
+#             if (( ! zustre_failed )); then
+#                 [[ "$zustre_output" == *"<Answer>SAFE</Answer>"* ]] || {
+#                     error_test zustre;
+#                     zustre_failed=1;
+#                 }
+#             fi
+#         fi
+#     else
+#         error_msg "Skipping Zustre: zustre installation, failed"
+#     fi
+# fi
 #################
 # Install kind2 #
 #################
